# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04\x66\x64\x63l\"3\n\x07Vector3\x12\x0c\n\x01x\x18\x01 \x02(\x02:\x01\x30\x12\x0c\n\x01y\x18\x02 \x02(\x02:\x01\x30\x12\x0c\n\x01z\x18\x03 \x02(\x02:\x01\x30\"\x97\x05\n\x04\x44\x61ta\x12\x11\n\tsystem_on\x18\x01 \x02(\x08\x12\t\n\x01t\x18\x02 \x01(\x05\x12\x10\n\x08t_system\x18\x03 \x01(\x02\x12\r\n\x05t_imu\x18\x04 \x01(\x02\x12\x10\n\x08\x66req_imu\x18\x05 \x01(\x05\x12\x1a\n\x03ypr\x18\x06 \x01(\x0b\x32\r.fdcl.Vector3\x12\x18\n\x01\x61\x18\x07 \x01(\x0b\x32\r.fdcl.Vector3\x12\x18\n\x01W\x18\x08 \x01(\x0b\x32\r.fdcl.Vector3\x12\x13\n\x0btemperature\x18\t \x01(\x02\x12\r\n\x05t_gps\x18\n \x01(\x02\x12\x10\n\x08\x66req_gps\x18\x0b \x01(\x05\x12\x1c\n\x05rtk_x\x18\x0c \x01(\x0b\x32\r.fdcl.Vector3\x12\x1c\n\x05rtk_v\x18\r \x01(\x0b\x32\r.fdcl.Vector3\x12\x1a\n\x03llh\x18\x0e \x01(\x0b\x32\r.fdcl.Vector3\x12\x0e\n\x06status\x18\x0f \x01(\x05\x12\x10\n\x08num_sats\x18\x10 \x01(\x05\x12\x13\n\x0butc_seconds\x18\x11 \x01(\x05\x12\x11\n\tutc_nanos\x18\x12 \x01(\x05\x12\x0e\n\x06t_ane1\x18\x13 \x01(\x02\x12\x11\n\tfreq_ane1\x18\x14 \x01(\x05\x12\x1f\n\x08uvw_ane1\x18\x15 \x01(\x0b\x32\r.fdcl.Vector3\x12\x11\n\ttemp_ane1\x18\x16 \x01(\x02\x12\x0e\n\x06t_ane2\x18\x17 \x01(\x02\x12\x11\n\tfreq_ane2\x18\x18 \x01(\x05\x12\x1f\n\x08uvw_ane2\x18\x19 \x01(\x0b\x32\r.fdcl.Vector3\x12\x11\n\ttemp_ane2\x18\x1a \x01(\x02\x12\x0e\n\x06t_cam1\x18\x1b \x01(\x02\x12\x11\n\tfreq_cam1\x18\x1c \x01(\x05\x12\x10\n\x08idx_cam1\x18\x1d \x01(\x05\x12\x0e\n\x06t_cam2\x18\x1e \x01(\x02\x12\x11\n\tfreq_cam2\x18\x1f \x01(\x05\x12\x10\n\x08idx_cam2\x18  \x01(\x05')



_VECTOR3 = DESCRIPTOR.message_types_by_name['Vector3']
_DATA = DESCRIPTOR.message_types_by_name['Data']
Vector3 = _reflection.GeneratedProtocolMessageType('Vector3', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR3,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:fdcl.Vector3)
  })
_sym_db.RegisterMessage(Vector3)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:fdcl.Data)
  })
_sym_db.RegisterMessage(Data)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTOR3._serialized_start=20
  _VECTOR3._serialized_end=71
  _DATA._serialized_start=74
  _DATA._serialized_end=737
# @@protoc_insertion_point(module_scope)
